services:
  liferay:
    image: liferay/dxp:2025.q1.4-lts
    ports:
      - 8080:8080
    volumes:
      - ./liferay/files:/mnt/liferay/files
      - liferay_data:/opt/liferay/data
    depends_on:
      postgres:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
      opensearch-node2:
        condition: service_healthy
  contentwizard:
    build:
      context: contentwizard
      dockerfile: Dockerfile
    image: liferay/ai-tasks-content-wizard-bun:1.0
    ports:
      - 3001:3001
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -k --silent --fail http://contentwizard:3001/ready || exit 1',
        ]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 20s
  opensearch-node1:
    build:
      context: opensearch
      dockerfile: Dockerfile
    image: liferay/ai-tasks-opensearch-node:1.0
    container_name: opensearch-node1
    environment:
      - cluster.name=liferay-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true=
      - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m'
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600
    volumes:
      - os_node1_data:/usr/share/opensearch/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -k --silent --fail http://opensearch-node1:9200/ || exit 1',
        ]
      interval: 10s
      timeout: 40s
      retries: 4
      start_period: 10s
  opensearch-node2:
    build:
      context: opensearch
      dockerfile: Dockerfile
    image: liferay/ai-tasks-opensearch-node:1.0
    container_name: opensearch-node2
    environment:
      - cluster.name=liferay-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m'
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - os_node2_data:/usr/share/opensearch/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -k --silent --fail http://opensearch-node2:9200/ || exit 1',
        ]
      interval: 10s
      timeout: 40s
      retries: 4
      start_period: 10s
  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    image: liferay/ai-tasks-postgres:1.0
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=liferay
      - POSTGRES_DB=lportal
      - POSTGRES_PASSWORD=L1freay$
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'lportal']
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
volumes:
  liferay_data:
  os_node1_data:
  os_node2_data:
  postgres_data: